### ISSUE TITLE
Fetch Data from Supabase

### ISSUE THREAD

**Issue by atharvnuthi** [JavascriptMick/nuxt3-boilerplate#1]
Hey! 
I really appreciate you making this boilerplate for the Authentication part. 
Could you add the fetch part too please? 
I am getting erros saying nuxt instance unavailable. 
The documentation is really poor on the nuxt-supabase website.

**Comment by JavascriptMick** [comment]
hi @atharvnuthi 
Glad you appreciate the repo.  I have decided to fetch data from the Supabase store via Prisma rather than via the Supabase API.  I just prefer Prisma as it makes it so easy to manage schema changes and generates all the types... and these types flow all the way through to the front end via TRPC.  Pretty happy with the setup although there are a lot of moving parts.  So I can't fulfil your request.  I hope you resolved your issue eventually.
