### ISSUE TITLE
sample to upload image to notes

### ISSUE THREAD

**Issue by musfandi** [JavascriptMick/nuxt3-boilerplate#10]
Any sample to upload image to notes

**Comment by JavascriptMick** [comment]
Hi @musfandi,

Thanks for your interest and your suggestion.

Short answer, look here: https://supabase.com/docs/guides/getting-started/tutorials/with-nuxt-3#bonus-profile-photos

I'm not keen to add this feature mostly because it can be done a bunch of different ways and will vary a lot depending on your application and scale (100s of images would likely require different solution than thousands of images).

If you want a pure Supabase solution, I have put a link to the relevant tutorial above, be aware though that on the free plan, Supabase only supports "Up to 1GB file storage".  That's not going to last long and will likely push most Saas projects over into the Pro tier (100GB file storage included).

If you figure it out and can share an open repo or other reference etc, send me the info and I will add it to the readme.

Regards,
Michael

**Comment by JavascriptMick** [comment]
@musfandi, I have added this as a feature request in the new Discord server (look for the 'feature-requests' channel.  Discord is here.. https://discord.gg/3hWPDTA4kD
