### ISSUE TITLE
Prisma

### ISSUE THREAD

**Issue by unstated-int** [JavascriptMick/nuxt3-boilerplate#4]
Hey!
I am building something similar and landed in your repo.
Thanks a lot, very cool! Thank you for sharing this.

I am trying to understand your work well.
Excuse me so much, can I ask you why you use Prism? Could it be done without it? 
Wouldn't Supabase still work properly with the API?

Thank you thank you!
Best

**Comment by fskarmeta** [comment]
Just wanted to use this issue to also thank you, this boilerplate has been very useful and we are using the exact same stack :)

**Comment by unstated-int** [comment]
@fskarmeta are you also using Prism?
Is it really indispensable? I hope to share with you soon what I have done, maybe it will be useful to you.

**Comment by fskarmeta** [comment]
@leonardoa yeah we are using prisma , it's because we prefer managing the database migrations and schemas via de prisma cli, and also with typescript and trpc the type safety is superior, with pure supabase you would have to generate the database types with the Superbase cli and reference them everywhere, also I find them kinda unreliable.

**Comment by unstated-int** [comment]
@fskarmeta Thank you so much for taking the time to respond and for all this information.
Much appreciate it.
:)

**Comment by JavascriptMick** [comment]
hi @leonardoa ,

Thanks for your question and thanks @fskarmeta  for your responses also.  Prisma is very important in my approach to this.  The generated Prisma types are used throughout the stack all the way to the front end code.  Having one set of types all the way through was an important considerataion and is why for example I have used TRPC rather than REST, so those types can flow through to the front end.

Having said that, you could do it without Prisma by generating your own types to represent the data structures and then altering the service layer code (https://github.com/JavascriptMick/nuxt3-boilerplate/tree/master/lib/services) to use the supabase Client rather than the Prisma client.  In fact the reason I put all of the DB manipulation and query into the service layer was to ensure that I could change my mind on the DB access approach.
