### ISSUE TITLE
Avaliable to small help

### ISSUE THREAD

**Issue by johanguse** [JavascriptMick/nuxt3-boilerplate#9]
I'm wondering if I could assist with minor modifications. I noticed a few areas in the header and page content that could be improved (centered)... Additionally, I'm thinking of adding 'prettier' and 'prettier-plugin-tailwindcss'. Lastly, updating the dependencies is another task I could undertake. Can I open a PR to your branch to fix the centered content?

I like this boilerplate. it appears to have great potential!

![image](https://github.com/JavascriptMick/nuxt3-boilerplate/assets/6184866/ff8d1cb7-9e17-4ffb-9403-e1069546a930)
![image](https://github.com/JavascriptMick/nuxt3-boilerplate/assets/6184866/56739eed-af53-4b9b-92cc-cea4a39e54b5)

**Comment by JavascriptMick** [comment]
Hi @johanguse ,

For sure, would appreciate any tweaks to the front end that make sense.  Raise a PR and I will definitely look at it.  re: additional stuff like prettier etc, you would need to convince me of the benefit.  I have tried to keep this thing as minimal as possible so that people can make their own choices without impediment.

Michael

**Comment by JavascriptMick** [comment]
Closing this.  PR's welcome if you have ideas.
